spring:
  ###activemq
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  ###rabbitmq
  rabbitmq:
    addresses: localhost:5672
    username: root
    password: 123456
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: manual
  ###kafka
  kafka:
    bootstrap-servers: http://127.0.0.1:9092
    producer:
      retries: 0
      linger: 1
      batch.size: 4096
      buffer.memory: 40960
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      enable-auto-commit: true
      auto.commit.interval: 100
      auto.offset.reset: earliest
      session.timeout: 6000
      group-id: default_consumer_group #群组ID
      concurrency: 10
      max.pollrecordes: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  ###rocketmq
  rocketmq:
    producer:
      isOnOff: on
      groupName: CicadaGroup
      namesrvAddr: 127.0.0.1:9876
      maxMessageSize: 4096
      sendMsgTimeout: 3000
      retryTimesWhenSendFailed: 2
    consumer:
      isOnOff: on
      groupName: CicadaGroup
      namesrvAddr: 127.0.0.1:9876
      topics: topic_test~*;topic_test2~*
      consumeThreadMin: 20
      consumeThreadMax: 64
      consumeMessageBatchMaxSize: 1
  ###mongodb
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test

##Redis
redis:
  cluster:
    address: 192.168.10.241:7000,192.168.10.241:7001,192.168.10.241:7002,192.168.10.241:7003,192.168.10.241:7004,192.168.10.241:7005
  sentinel:
    master: redis-master
    nodes: 192.168.10.241:25379
  single:
    ip: 127.0.0.1
    port: 6379
  password: foobared
  timeout: 6000
  maxTotal: 30
  maxIdle: 30
  minIdle: 5
  maxWaitMillis: 1000
  maxRedirections: 5
